version: '3.8'

services:
  api:
    build: ./backend
    container_name: devdocs_api
    ports:
      - "3000:3000"
    command: ["node", "dist/main.js"]   # 🔥 force override
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: devdocs
      REDIS_HOST: redis

  worker:
    build: ./backend
    command: node dist/worker.js
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: devdocs
      REDIS_HOST: redis

  db:
    image: postgres:15
    container_name: devdocs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdocs
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: devdocs_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"