version: '3.8'

services:

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    depends_on:
      - redis

  payment-service:
    build: ./payment-service
    ports:
      - "3002:3002"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: devdocs_frontend
    ports:
      - "3001:3000"
    command: ["node", "server.js"]  # 🔥 force override
    depends_on:
      - api
  
  api:
    build: ./backend
    container_name: devdocs_api
    ports:
      - "3000:3000"
    command: ["node", "dist/main.js"]   # 🔥 force override
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: devdocs
      REDIS_HOST: redis

  worker:
    build: ./backend
    command: node dist/worker.js
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: devdocs
      REDIS_HOST: redis

  db:
    image: postgres:15
    container_name: devdocs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdocs
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: devdocs_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"